/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
import dao.ThongKeDAO;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author lehoa
 */
public class ThongKeJPanel extends javax.swing.JPanel {
private ThongKeDAO tkDAO = new ThongKeDAO();
    private DefaultTableModel tableModel;
    /**
     * Creates new form ThongKeJPanel
     */
    public ThongKeJPanel() {
        initComponents();
        tableModel = (DefaultTableModel) tblThongKe.getModel();
        
        // 1. Thiết lập ngày mặc định là ngày hôm nay
        jDateChooser_Start.setDate(new Date());
        jDateChooser_End.setDate(new Date());
        
        // 2. Load dữ liệu lần đầu
        loadData();
        
        // 3. Sự kiện: Khi người dùng thay đổi ngày, bảng tự cập nhật
        jDateChooser_Start.addPropertyChangeListener(evt -> {
            if ("date".equals(evt.getPropertyName())) loadData();
        });
        jDateChooser_End.addPropertyChangeListener(evt -> {
            if ("date".equals(evt.getPropertyName())) loadData();
        });
    }
private void loadData() {
    // 1. Kiểm tra nếu chưa chọn ngày thì không thực hiện
    if (jDateChooser_Start.getDate() == null || jDateChooser_End.getDate() == null) {
        return;
    }

    // 2. Định dạng ngày để gửi xuống SQL (yyyy-MM-dd)
    SimpleDateFormat sdfSql = new SimpleDateFormat("yyyy-MM-dd");
    String start = sdfSql.format(jDateChooser_Start.getDate());
    String end = sdfSql.format(jDateChooser_End.getDate());

    // 3. Làm sạch bảng trước khi nạp dữ liệu mới
    tableModel.setRowCount(0);

    // 4. Gọi DAO lấy danh sách hóa đơn
    List<Object[]> list = tkDAO.getDSHoaDon(start, end);
    
    int stt = 1;
    double tongDoanhThu = 0;
    
    // Định dạng hiển thị: Ngày (dd/MM/yyyy) và Tiền (có dấu phẩy)
    SimpleDateFormat displayDate = new SimpleDateFormat("dd/MM/yyyy HH:mm");

    for (Object[] row : list) {
        double soTien = (double) row[2]; // row[2] là TongTien từ DAO
        tongDoanhThu += soTien;

        tableModel.addRow(new Object[]{
            stt++,                                  // Cột STT
            "HD" + row[0],                          // Cột Mã HĐ (row[0] là MaHD)
            displayDate.format((Date) row[1]),      // Cột Ngày lập (row[1] là NgayLap)
            String.format("%,.0f VNĐ", soTien)      // Cột Tổng tiền
        });
    }

    // 5. Hiển thị tổng tiền lên Label jlbTongTien
    jlbTongTien.setText("<html><b style='color:black;'>Tổng doanh thu: </b>"
            + "<b style='color:red; font-size:16px;'>" + String.format("%,.0f VNĐ", tongDoanhThu) + "</b></html>");
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblThongKe = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jDateChooser_Start = new com.toedter.calendar.JDateChooser();
        jDateChooser_End = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlbTongTien = new javax.swing.JLabel();

        tblThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "Mã HĐ", "Ngày lập", "Tổng tiền"
            }
        ));
        tblThongKe.setToolTipText("");
        jScrollPane1.setViewportView(tblThongKe);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 204, 255));
        jLabel14.setText("Thống kê hóa đơn");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Từ ngày:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Đến ngày:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jDateChooser_Start, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jDateChooser_End, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addComponent(jlbTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jlbTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooser_End;
    private com.toedter.calendar.JDateChooser jDateChooser_Start;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbTongTien;
    private javax.swing.JTable tblThongKe;
    // End of variables declaration//GEN-END:variables
}
