/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
import dao.ThongKeDAO;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author lehoa
 */
public class ThongKeCaLamJPanel extends javax.swing.JPanel {
private ThongKeDAO tkDAO = new ThongKeDAO();
    private DefaultTableModel tableModel;
    /**
     * Creates new form ThongKeJPanel
     */
    public ThongKeCaLamJPanel() {
        initComponents();
        tableModel = (DefaultTableModel) tblThongKeCaLam.getModel();
        
        // 1. Thiết lập ngày mặc định là ngày hôm nay
        jDateChooser_Start.setDate(new Date());
        jDateChooser_End.setDate(new Date());
        
        // 2. Load dữ liệu lần đầu
        loadData();
        
        // 3. Sự kiện: Khi người dùng thay đổi ngày, bảng tự cập nhật
        jDateChooser_Start.addPropertyChangeListener(evt -> {
            if ("date".equals(evt.getPropertyName())) loadData();
        });
        jDateChooser_End.addPropertyChangeListener(evt -> {
            if ("date".equals(evt.getPropertyName())) loadData();
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblThongKeCaLam = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jDateChooser_Start = new com.toedter.calendar.JDateChooser();
        jDateChooser_End = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlbTongTien = new javax.swing.JLabel();

        tblThongKeCaLam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã ca", "Giờ bắt đầu", "Giờ kết thúc", "Tiền mở ca", "Tiền mặt", "Chuyển khoản", "Doanh thu", "Mã nhân viên", "Role"
            }
        ));
        tblThongKeCaLam.setToolTipText("");
        jScrollPane1.setViewportView(tblThongKeCaLam);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 204, 255));
        jLabel14.setText("Thống kê ca làm");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Từ ngày:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Đến ngày:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooser_Start, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser_End, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jlbTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jlbTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooser_End;
    private com.toedter.calendar.JDateChooser jDateChooser_Start;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbTongTien;
    private javax.swing.JTable tblThongKeCaLam;
    // End of variables declaration//GEN-END:variables
private void loadData() {
    if (jDateChooser_Start.getDate() == null || jDateChooser_End.getDate() == null) {
        return;
    }

    SimpleDateFormat sdfSql = new SimpleDateFormat("yyyy-MM-dd");
    String start = sdfSql.format(jDateChooser_Start.getDate());
    String end = sdfSql.format(jDateChooser_End.getDate());

    tableModel.setRowCount(0);
    List<Object[]> list = tkDAO.getDSThongKeCa(start, end); 
    
    int stt = 1;
    double tongDoanhThuKy = 0;
    SimpleDateFormat displayDate = new SimpleDateFormat("dd/MM/yyyy HH:mm");

    for (Object[] row : list) {
        double tienMo   = row[3] != null ? ((Number) row[3]).doubleValue() : 0;
        double tienMat  = row[4] != null ? ((Number) row[4]).doubleValue() : 0;
        double tienCK   = row[5] != null ? ((Number) row[5]).doubleValue() : 0;
        double doanhThu = row[6] != null ? ((Number) row[6]).doubleValue() : 0;
        
        tongDoanhThuKy += doanhThu;

        tableModel.addRow(new Object[]{
            stt++,                                  // 0: STT
            "CA" + row[0],                          // 1: Mã ca
            displayDate.format((java.util.Date) row[1]), // 2: Giờ BD
            row[2] != null ? displayDate.format((java.util.Date) row[2]) : "Đang trực", // 3: Giờ KT
            String.format("%,.0f", tienMo),         // 4: Tiền mở ca
            String.format("%,.0f", tienMat),        // 5: Tiền mặt
            String.format("%,.0f", tienCK),         // 6: Chuyển khoản
            String.format("%,.0f VNĐ", doanhThu),   // 7: Doanh thu
            row[7],                                 // 8: Mã nhân viên (Mới)
            row[8] != null ? row[8] : "N/A"         // 9: Role (Mới)
        });
    }

    jlbTongTien.setText("<html><b style='color:black;'>Tổng doanh thu kỳ: </b>"
            + "<b style='color:red; font-size:16px;'>" + String.format("%,.0f VNĐ", tongDoanhThuKy) + "</b></html>");
    
    formatTable(); // Gọi hàm định dạng sau khi load dữ liệu
}
    private void formatTable() {
    // Renderer cho căn phải (Tiền)
    javax.swing.table.DefaultTableCellRenderer rightRenderer = new javax.swing.table.DefaultTableCellRenderer();
    rightRenderer.setHorizontalAlignment(javax.swing.JLabel.RIGHT);
    
    // Renderer cho căn giữa (Mã, STT, Role)
    javax.swing.table.DefaultTableCellRenderer centerRenderer = new javax.swing.table.DefaultTableCellRenderer();
    centerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);

    // Căn giữa STT (0), Mã ca (1), Mã NV (8), Role (9)
    tblThongKeCaLam.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
    tblThongKeCaLam.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
    tblThongKeCaLam.getColumnModel().getColumn(8).setCellRenderer(centerRenderer);
    tblThongKeCaLam.getColumnModel().getColumn(9).setCellRenderer(centerRenderer);

    // Căn phải cho các cột tiền (4, 5, 6, 7)
    for (int i = 4; i <= 7; i++) {
        tblThongKeCaLam.getColumnModel().getColumn(i).setCellRenderer(rightRenderer);
    }
    
    // Tùy chỉnh độ rộng cột (Ví dụ)
    tblThongKeCaLam.getColumnModel().getColumn(0).setPreferredWidth(40);  // STT
    tblThongKeCaLam.getColumnModel().getColumn(1).setPreferredWidth(60);  // Mã ca
    tblThongKeCaLam.getColumnModel().getColumn(9).setPreferredWidth(100); // Role

}
}
