/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;



import dao.SanPhamDAO;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import model.SanPham;
import java.awt.Image;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
/**
 *
 * 
 */
public class ThucDonJPanel extends javax.swing.JPanel {

    private DefaultTableModel tableModel;
private DefaultTableModel dmTableModel; // <--- THÊM DÒNG NÀY
private SanPhamDAO sanPhamDAO;
private dao.DanhMucDAO dmDAO; // <--- THÊM DÒNG NÀY
    /**
     * Creates new form NhanVienJPanel
     */
    public ThucDonJPanel() {
        initComponents();
    sanPhamDAO = new SanPhamDAO();
    dmDAO = new dao.DanhMucDAO(); // Khởi tạo DAO mới
    tableModel = (DefaultTableModel) tbSanPham.getModel();
    dmTableModel = (DefaultTableModel) tbDanhMuc.getModel(); // Lấy model của bảng danh mục
    
    loadDataToTable();
    loadDanhMucToTable(); // Nạp dữ liệu vào tbDanhMuc
    loadDanhMucToCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtTimKiemID = new javax.swing.JTextField();
        btnTimKiemID = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTenSP = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        cboDanhMuc = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btnLamMoi = new javax.swing.JButton();
        btnChonAnh = new javax.swing.JButton();
        jLabel_IMG = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtIMG_URL = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSanPham = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtTenDanhMuc = new javax.swing.JTextField();
        btnThemDM = new javax.swing.JButton();
        btnXoaDM = new javax.swing.JButton();
        btnSuaDM = new javax.swing.JButton();
        btnLamMoiDM = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbDanhMuc = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Tìm kiếm ID");

        txtTimKiemID.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtTimKiemID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemIDActionPerformed(evt);
            }
        });

        btnTimKiemID.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnTimKiemID.setText("Tìm kiếm");
        btnTimKiemID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTimKiemID, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTimKiemID)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTimKiemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiemID))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Tên món:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Đơn giá:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        txtTenSP.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtTenSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenSPActionPerformed(evt);
            }
        });

        txtDonGia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        btnThem.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Danh mục:");

        btnLamMoi.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnChonAnh.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnChonAnh.setText("Chọn ảnh");
        btnChonAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonAnhActionPerformed(evt);
            }
        });

        jLabel_IMG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_IMG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("IMG_URL:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel_IMG, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenSP)
                    .addComponent(txtDonGia)
                    .addComponent(cboDanhMuc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnThem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnXoa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLamMoi))
                            .addComponent(btnChonAnh))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIMG_URL)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnChonAnh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtIMG_URL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem)
                            .addComponent(btnXoa)
                            .addComponent(btnSua)
                            .addComponent(btnLamMoi)))
                    .addComponent(jLabel_IMG, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbSanPham.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tbSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Danh mục", "Đơn giá", "Danh mục"
            }
        ));
        tbSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbSanPham);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 204, 255));
        jLabel5.setText("Quản lý thực đơn");

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("Tên danh mục:");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        txtTenDanhMuc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtTenDanhMuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenDanhMucActionPerformed(evt);
            }
        });

        btnThemDM.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnThemDM.setText("Thêm");
        btnThemDM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDMActionPerformed(evt);
            }
        });

        btnXoaDM.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnXoaDM.setText("Xóa");
        btnXoaDM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaDMActionPerformed(evt);
            }
        });

        btnSuaDM.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSuaDM.setText("Sửa");
        btnSuaDM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaDMActionPerformed(evt);
            }
        });

        btnLamMoiDM.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnLamMoiDM.setText("Làm mới");
        btnLamMoiDM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiDMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel13))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenDanhMuc)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnThemDM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoaDM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSuaDM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLamMoiDM)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtTenDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemDM)
                    .addComponent(btnXoaDM)
                    .addComponent(btnSuaDM)
                    .addComponent(btnLamMoiDM))
                .addGap(68, 68, 68)
                .addComponent(jLabel15))
        );

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tbDanhMuc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã danh mục", "Tên danh mục", "Số món "
            }
        ));
        tbDanhMuc.setToolTipText("");
        tbDanhMuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDanhMucMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbDanhMuc);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 204, 255));
        jLabel14.setText("Danh mục");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(246, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemIDActionPerformed
String idText = txtTimKiemID.getText().trim();
    if (idText.isEmpty()) {
        loadDataToTable(); // Nếu trống thì hiện tất cả
        return;
    }

    try {
        int id = Integer.parseInt(idText);
        SanPham sp = sanPhamDAO.getSanPhamById(id);
        if (sp != null) {
            // Đổ lên form
            txtTenSP.setText(sp.getTenSP());
            txtDonGia.setText(String.valueOf(sp.getDonGia()));
            txtIMG_URL.setText(sp.getImgUrl());
            cboDanhMuc.setSelectedIndex(sp.getMaDM() - 1);
            displayImage(sp.getImgUrl()); // Hiện ảnh
            
            // Chọn dòng đó trên bảng
            for (int i = 0; i < tbSanPham.getRowCount(); i++) {
                if ((int)tbSanPham.getValueAt(i, 0) == id) {
                    tbSanPham.setRowSelectionInterval(i, i);
                    break;
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy sản phẩm có ID: " + id);
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "ID phải là số!");
    }
    }//GEN-LAST:event_btnTimKiemIDActionPerformed

    private void tbSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSanPhamMouseClicked
      int row = tbSanPham.getSelectedRow();
        if (row >= 0) {
            int maSP = (int) tableModel.getValueAt(row, 0);
            SanPham sp = sanPhamDAO.getSanPhamById(maSP);
            if (sp != null) {
                txtTenSP.setText(sp.getTenSP());
                txtDonGia.setText(String.valueOf(sp.getDonGia()));
                txtIMG_URL.setText(sp.getImgUrl());
                cboDanhMuc.setSelectedItem(tableModel.getValueAt(row, 2));
                displayImage(sp.getImgUrl()); // HIỂN THỊ ẢNH KHI CLICK DÒNG
            }
        }
    }//GEN-LAST:event_tbSanPhamMouseClicked

    private void txtTimKiemIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemIDActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // 1. Xóa các ô nhập liệu văn bản
    txtTenSP.setText("");
    txtDonGia.setText("");
    txtIMG_URL.setText("");
    txtTimKiemID.setText("");
    
    // 2. Đưa ComboBox về mục đầu tiên
    if (cboDanhMuc.getItemCount() > 0) {
        cboDanhMuc.setSelectedIndex(0);
    }
    
    // 3. Xóa hình ảnh hiển thị trên Label
    jLabel_IMG.setIcon(null);
    jLabel_IMG.setText("No Image");
    
    // 4. Bỏ chọn dòng trong bảng sản phẩm
    tbSanPham.clearSelection();
    
    // 5. Nạp lại dữ liệu từ DB để đảm bảo bảng hiển thị đủ món (phòng trường hợp đang tìm kiếm)
    loadDataToTable();
    
    JOptionPane.showMessageDialog(this, "Đã làm mới form sản phẩm!");
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
     int row = tbSanPham.getSelectedRow();
    if (row < 0) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn món cần sửa!");
        return;
    }

    try {
        int maSP = (int) tableModel.getValueAt(row, 0);
        String ten = txtTenSP.getText().trim();
        double gia = Double.parseDouble(txtDonGia.getText().trim());
        String img = txtIMG_URL.getText().trim();
        int maDM = cboDanhMuc.getSelectedIndex() + 1;

        SanPham sp = new SanPham(maSP, ten, gia, maDM, img);
        if (sanPhamDAO.updateSanPham(sp)) {
            JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
            loadDataToTable();
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi dữ liệu!");
    }   
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
       int row = tbSanPham.getSelectedRow();
    if (row >= 0) {
        int id = (int) tableModel.getValueAt(row, 0);
        
        // 1. Lấy thông tin sản phẩm để biết đường dẫn ảnh trước khi xóa khỏi DB
        SanPham sp = sanPhamDAO.getSanPhamById(id);
        
        if (sp != null) {
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa sản phẩm này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
            
            if (confirm == JOptionPane.YES_OPTION) {
                // 2. Xóa sản phẩm trong Database
                if (sanPhamDAO.deleteSanPham(id)) {
                    
                    // 3. Xóa tệp ảnh vật lý
                    deleteProductImage(sp.getImgUrl());
                    
                    JOptionPane.showMessageDialog(this, "Xóa sản phẩm và ảnh thành công!");
                    loadDataToTable();
                    resetForm();
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa thất bại!");
                }
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm cần xóa trên bảng!");
    }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
     try {
        String ten = txtTenSP.getText().trim();
        String giaStr = txtDonGia.getText().trim();
        String sourceImgPath = txtIMG_URL.getText().trim(); // Đường dẫn tuyệt đối từ JFileChooser

        if(ten.isEmpty() || giaStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên và giá!");
            return;
        }

        // BƯỚC QUAN TRỌNG: Copy ảnh vào folder dự án và lấy đường dẫn tương đối
        String relativePath = saveImageToFolder(sourceImgPath);

        // Lấy MaDM từ Database (đã cập nhật ở bước trước)
        int maDM = 1;
        String tenDMSelected = cboDanhMuc.getSelectedItem().toString();
        dao.DanhMucDAO dmDAO = new dao.DanhMucDAO();
        for(model.DanhMuc dm : dmDAO.getAllDanhMuc()) {
            if(dm.getTenDanhMuc().equals(tenDMSelected)) {
                maDM = dm.getMaDM();
                break;
            }
        }

        // Lưu vào Database với relativePath (ví dụ: img/hinh_anh.jpg)
        SanPham sp = new SanPham(0, ten, Double.parseDouble(giaStr), maDM, relativePath);
        if (sanPhamDAO.addSanPham(sp)) {
            JOptionPane.showMessageDialog(this, "Thêm món và lưu ảnh thành công!");
            loadDataToTable();
            resetForm();
        }
    } catch (Exception e) { 
        JOptionPane.showMessageDialog(this, "Lỗi hệ thống: " + e.getMessage()); 
    }
    }//GEN-LAST:event_btnThemActionPerformed

    private void txtTenSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenSPActionPerformed

    private void btnChonAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonAnhActionPerformed
JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            txtIMG_URL.setText(selectedFile.getAbsolutePath());
            displayImage(selectedFile.getAbsolutePath());
        }       // TODO add your handling code here:
    }//GEN-LAST:event_btnChonAnhActionPerformed

    private void txtTenDanhMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenDanhMucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenDanhMucActionPerformed

    private void btnThemDMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDMActionPerformed
        // TODO add your handling code here:
        String ten = txtTenDanhMuc.getText().trim();
    if (ten.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Tên danh mục không được để trống!");
        return;
    }
    if (dmDAO.addDanhMuc(ten)) {
        loadDanhMucToTable(); // Cập nhật bảng DM
        loadDanhMucToCombo(); // Cập nhật ComboBox của Sản phẩm
        txtTenDanhMuc.setText("");
    }
    }//GEN-LAST:event_btnThemDMActionPerformed

    private void btnXoaDMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaDMActionPerformed
        // TODO add your handling code here:
        int row = tbDanhMuc.getSelectedRow();
    if (row < 0) return;
    
    int ma = (int) dmTableModel.getValueAt(row, 0);
    int soMon = (int) dmTableModel.getValueAt(row, 2); // Cột số lượng món
    
    if (soMon > 0) {
        JOptionPane.showMessageDialog(this, "Không thể xóa danh mục đang chứa sản phẩm!");
        return;
    }
    
    if (JOptionPane.showConfirmDialog(this, "Xác nhận xóa danh mục này?") == JOptionPane.YES_OPTION) {
        if (dmDAO.deleteDanhMuc(ma)) {
            loadDanhMucToTable();
            loadDanhMucToCombo();
        }
    }
    }//GEN-LAST:event_btnXoaDMActionPerformed

    private void btnSuaDMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaDMActionPerformed
        // TODO add your handling code here:
        int row = tbDanhMuc.getSelectedRow();
    if (row < 0) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn danh mục cần sửa trên bảng!");
        return;
    }
    int ma = (int) dmTableModel.getValueAt(row, 0);
    String tenMoi = txtTenDanhMuc.getText().trim();
    
    if (dmDAO.updateDanhMuc(ma, tenMoi)) {
        JOptionPane.showMessageDialog(this, "Cập nhật danh mục thành công!");
        loadDanhMucToTable();
        loadDanhMucToCombo();
        loadDataToTable(); // Load lại bảng sản phẩm để cập nhật tên danh mục mới (nếu đang JOIN)
    }
    }//GEN-LAST:event_btnSuaDMActionPerformed

    private void btnLamMoiDMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiDMActionPerformed
        // TODO add your handling code here:
        // 1. Xóa trắng ô tên danh mục
    txtTenDanhMuc.setText("");
    
    // 2. Bỏ chọn dòng trên bảng danh mục
    tbDanhMuc.clearSelection();
    
    // 3. Nạp lại bảng danh mục để cập nhật số lượng món mới nhất
    loadDanhMucToTable();
    
    JOptionPane.showMessageDialog(this, "Đã làm mới form danh mục!");
    }//GEN-LAST:event_btnLamMoiDMActionPerformed

    private void tbDanhMucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDanhMucMouseClicked
        // TODO add your handling code here:
        int row = tbDanhMuc.getSelectedRow();
    if (row >= 0) {
        txtTenDanhMuc.setText(dmTableModel.getValueAt(row, 1).toString());
    }
    }//GEN-LAST:event_tbDanhMucMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonAnh;
    private javax.swing.JButton btnChonAnh1;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLamMoiDM;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnSua1;
    private javax.swing.JButton btnSuaDM;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThem1;
    private javax.swing.JButton btnThemDM;
    private javax.swing.JButton btnTimKiemID;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoa1;
    private javax.swing.JButton btnXoaDM;
    private javax.swing.JComboBox<String> cboDanhMuc;
    private javax.swing.JComboBox<String> cboDanhMuc1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_IMG;
    private javax.swing.JLabel jLabel_IMG1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbDanhMuc;
    private javax.swing.JTable tbSanPham;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtDonGia1;
    private javax.swing.JTextField txtIMG_URL;
    private javax.swing.JTextField txtIMG_URL1;
    private javax.swing.JTextField txtTenDanhMuc;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtTenSP1;
    private javax.swing.JTextField txtTimKiemID;
    // End of variables declaration//GEN-END:variables

private void loadDataToTable() {
        tableModel.setRowCount(0);
        List<SanPham> list = sanPhamDAO.getAllSanPham();
        for (SanPham sp : list) {
            tableModel.addRow(new Object[]{
                sp.getMaSP(), sp.getTenSP(), sp.getTenDM(), sp.getDonGia(), sp.getTenDM()
            });
        }
    }
private void loadDanhMucToCombo() {
    cboDanhMuc.removeAllItems();
    dao.DanhMucDAO dmDAO = new dao.DanhMucDAO();
    List<model.DanhMuc> list = dmDAO.getAllDanhMuc();
    for (model.DanhMuc dm : list) {
        cboDanhMuc.addItem(dm.toString()); // Hoặc add cả object dm nếu bạn dùng ComboBox<DanhMuc>
    }
}
   private void resetForm() {
        txtTenSP.setText("");
        txtDonGia.setText("");
        txtIMG_URL.setText("");
        txtTimKiemID.setText("");
        jLabel_IMG.setIcon(null);
        tbSanPham.clearSelection();
    }
   // Hàm hiển thị ảnh lên Label từ đường dẫn URL
public void displayImage(String imgPath) {
    if (imgPath == null || imgPath.isEmpty()) {
        jLabel_IMG.setIcon(null);
        jLabel_IMG.setText("No Image");
        return;
    }
    try {
        // Ưu tiên tìm trong thư mục dự án trước
        File file = new File(imgPath);
        if (!file.exists()) {
            file = new File(System.getProperty("user.dir") + File.separator + imgPath);
        }

        if (file.exists()) {
            ImageIcon imageIcon = new ImageIcon(file.getAbsolutePath());
            
            // CỐ ĐỊNH KÍCH THƯỚC: Thay 180 bằng kích thước Label bạn muốn
            int width = 180; 
            int height = 180;

            Image image = imageIcon.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
            jLabel_IMG.setIcon(new ImageIcon(image));
            jLabel_IMG.setText(""); 
        } else {
            jLabel_IMG.setIcon(null);
            jLabel_IMG.setText("File not found");
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}
private String saveImageToFolder(String sourcePath) {
    try {
        if (sourcePath == null || sourcePath.isEmpty()) return "";

        File sourceFile = new File(sourcePath);
        // Tạo thư mục "img" nếu chưa tồn tại trong dự án
        Path folderPath = Paths.get("img");
        if (!Files.exists(folderPath)) {
            Files.createDirectories(folderPath);
        }

        // Tạo đường dẫn đích: img/tên_file_gốc
        Path targetPath = folderPath.resolve(sourceFile.getName());
        
        // Thực hiện copy file (ghi đè nếu trùng tên)
        Files.copy(sourceFile.toPath(), targetPath, StandardCopyOption.REPLACE_EXISTING);
        
        // Trả về đường dẫn tương đối để lưu vào DB (ví dụ: img/cf_den.jpg)
        return "img/" + sourceFile.getName();
    } catch (Exception e) {
        e.printStackTrace();
        return sourcePath; // Nếu lỗi thì trả về đường dẫn cũ
    }
}
private void deleteProductImage(String imgPath) {
    if (imgPath == null || imgPath.isEmpty()) {
        return;
    }
    
    try {
        // Tạo đối tượng File từ đường dẫn lưu trong DB
        File file = new File(imgPath);
        
        // Nếu đường dẫn trong DB là tương đối (img/abc.jpg), cần trỏ đúng vào thư mục dự án
        if (!file.isAbsolute()) {
            file = new File(System.getProperty("user.dir") + File.separator + imgPath);
        }
        
        // Kiểm tra và thực hiện xóa
        if (file.exists()) {
            if (file.delete()) {
                System.out.println("Đã xóa ảnh: " + file.getAbsolutePath());
            } else {
                System.err.println("Không thể xóa ảnh (có thể tệp đang được sử dụng).");
            }
        }
    } catch (Exception e) {
        System.err.println("Lỗi khi xóa ảnh: " + e.getMessage());
    }
}
private void loadDanhMucToTable() {
    dmTableModel.setRowCount(0);
    List<Object[]> list = dmDAO.getDanhMucWithCount();
    for (Object[] row : list) {
        dmTableModel.addRow(row);
    }
}
}

